/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sapaiada;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaop
 */
public class ListaFuncionarios extends javax.swing.JFrame {
        
    private ListaFuncionarios() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private static ListaFuncionarios listFunc;
    public static ListaFuncionarios getListFunc(){
        if(listFunc == null){
            listFunc = new ListaFuncionarios();
        }
        return listFunc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabFuncionarios = new javax.swing.JTable();
        cmbItemBusca = new javax.swing.JComboBox<>();
        rotBuscarPor = new javax.swing.JLabel();
        cxBuscar = new javax.swing.JTextField();
        btVoltar = new javax.swing.JButton();
        btAdicionar = new javax.swing.JButton();
        btBusca = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "EMAIL", "CARGO", "IDLOJA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabFuncionarios);

        cmbItemBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "escolha uma opção", "Id", "Nome", "Cargo" }));

        rotBuscarPor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotBuscarPor.setText("BUSCAR POR:");

        btVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btVoltar.setText("VOLTAR");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAdicionar.setText("ADICIONAR");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btBusca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btBusca.setText("BUSCAR");
        btBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaActionPerformed(evt);
            }
        });

        btDeletar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btDeletar.setText("DELETAR");
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbItemBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDeletar)
                .addGap(123, 123, 123)
                .addComponent(btAdicionar)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBusca)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbItemBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotBuscarPor)
                    .addComponent(cxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBusca)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltar)
                    .addComponent(btAdicionar)
                    .addComponent(btDeletar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        limpar();
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaActionPerformed
        int pos = cmbItemBusca.getSelectedIndex();
        Conexao.getCon().executaBuscaFunc(pos, cxBuscar.getText());
        limpar();
        listarFunc(pos);
    }//GEN-LAST:event_btBuscaActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        AdicionarFuncionario.getAddFuncUnic().setVisible(true);
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        deletarFunc();
    }//GEN-LAST:event_btDeletarActionPerformed
    
    public void listarFunc(int pos) {
        Banco.getBancoRoupaUnic().getBdFuncionario().clear();
        Conexao.getCon().executaBuscaFunc(pos, cxBuscar.getText());
        DefaultTableModel tabModel = (DefaultTableModel) tabFuncionarios.getModel();
        int posLin = 0;
        tabModel.setRowCount(posLin);
        for (Funcionario f : Banco.getBancoRoupaUnic().getBdFuncionario()) {
            tabModel.insertRow(posLin, new Object[]{f.getIdFunc(), f.getNomeFunc(), f.getEmail(), f.getCargFunc(), f.getIdLoja()});
            posLin++;
        }
    }
    
    public void deletarFunc(){
        if (tabFuncionarios.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(
                    null,
                    "Selecione algum violão na tabela!!",
                    "Atenção!!",
                    1);
        else{
            Conexao.getCon().deletaFunc((int) tabFuncionarios.getValueAt(tabFuncionarios.getSelectedRow(), 0));
            JOptionPane.showMessageDialog(
                    null,
                    "Funcionario deletado com sucesso!",
                    "Atenção!!",
                    1);
        }
    }
    
    public javax.swing.JButton getBtAdicionar(){
        return btAdicionar;
    }

    public javax.swing.JButton getBtDeletar(){
        return btDeletar;
    }
    public void limpar(){
        cxBuscar.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btBusca;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cmbItemBusca;
    private javax.swing.JTextField cxBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rotBuscarPor;
    private javax.swing.JTable tabFuncionarios;
    // End of variables declaration//GEN-END:variables
}
