package sapaiada;

import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    private int log = -1;
    private Cliente cli = new Cliente();
    private Funcionario fun = new Funcionario();
    private Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
  
    private static Login loginUnic;
    public static Login getLoginUnic(){
        if(loginUnic == null){
            loginUnic = new Login();
        }
        return loginUnic;
    }

    public void setLog(int log){
        this.log = log;
    }
    
    public int getLog(){
        return log;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotEmail = new javax.swing.JLabel();
        rotSenha = new javax.swing.JLabel();
        cxEmail = new javax.swing.JTextField();
        btLogin = new javax.swing.JButton();
        cxSenha = new javax.swing.JPasswordField();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LOGIN");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        rotEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotEmail.setText("EMAIL:");

        rotSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotSenha.setText("SENHA:");

        btLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLogin.setText("LOGIN");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        btVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btVoltar.setText("VOLTAR");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btVoltar)
                        .addGap(56, 56, 56)
                        .addComponent(btLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rotEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rotSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxEmail)
                            .addComponent(cxSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotEmail)
                    .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotSenha)
                    .addComponent(cxSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLogin)
                    .addComponent(btVoltar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        Conexao.getCon().executaBuscaFunc(0, "");
        for(Funcionario f : Banco.getBancoRoupaUnic().getBdFuncionario()){
            if(cxEmail.getText().equals(f.getEmail())){
                if(cxSenha.getText().equals(f.getSenha())){
                    if(f.getCargFunc().equals("Chefe")){
                        log = 2;
                    }
                    else{
                        log = 1;
                    }
                    fun.setIdFunc(f.getIdFunc());
                    JOptionPane.showMessageDialog(null, "Logou com sucesso!",
                "Sucesso", 1);
                    limpar();
                    dispose();
                    break;
                }
                else{
                    JOptionPane.showMessageDialog(null, "Senha ou email incorreto",
                "Erro", 1);
                    limpar();
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Senha ou email incorreto",
                "Erro", 1);
        limpar();
        Conexao.getCon().executaBuscaCliente();
        for(Cliente c : Banco.getBancoRoupaUnic().getBdCliente()){
            if(cxEmail.getText().equals(c.getEmailCliente())){
                if(cxSenha.getText().equals(c.getSenhaCliente())){
                    log = 0;
                    cli.setIdCliente(c.getIdCliente());
                    cli.setNomeCliente(c.getNomeCliente());
                    cli.setTeleCliente(c.getTeleCliente());
                    JOptionPane.showMessageDialog(null, "Logou com sucesso!",
                "Sucesso", 1);
                    dispose();
                    limpar();
                    break;
                }
                else{
                    JOptionPane.showMessageDialog(null, "Senha ou email incorreto",
                "Erro", 1);
                    limpar();
                }
            }
        }
        Principal.getPrincipalUnic().botoesCertos(log);
    }//GEN-LAST:event_btLoginActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    public Cliente getCliente(){
        return cli;
    }
    
    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        limpar();
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    public void limpar(){
        cxEmail.setText("");
        cxSenha.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField cxEmail;
    private javax.swing.JPasswordField cxSenha;
    private javax.swing.JLabel rotEmail;
    private javax.swing.JLabel rotSenha;
    // End of variables declaration//GEN-END:variables
}
